package scg

import (
	"strconv"
	"strings"
)

// String renders the expression as SNOMED CT Compositional Grammar.
//
// The output parses back to an equal expression, which is the property
// FuzzParseRenderParse checks on every input the fuzzer reaches. That is what
// makes it safe to round-trip an expression through text — storing it, putting it
// in a FHIR Coding, sending it somewhere — rather than only reading one.
//
// # It is not "the canonical form"
//
// The SNOMED CT glossary mentions a canonical form, "generated by removing
// whitespace and terms from an expression and arranging the focus concepts,
// refinements, attributes, and attribute groups in a standard order". The
// Compositional Grammar specification does not define that order: the word
// canonical does not appear in any of its sections. So there is nothing to
// target, and this deliberately does NOT reorder anything.
//
// What it produces is a FAITHFUL rendering — same order, same terms, normalized
// whitespace. Two expressions that mean the same thing but were written with their
// attributes in a different order render differently, and that is honest: this
// package cannot claim an ordering the specification does not give it. If you need
// a comparison key, sort before rendering and say in your own code what the sort
// means.
//
// # Choices worth knowing
//
//   - The definition status is always emitted, including the "===" default. A
//     serialization should mean one thing without the reader having to know which
//     default applies.
//   - Terms are kept. They carry no meaning — the SCTID does — but dropping them
//     would make the output disagree with its input for no gain, and keeping them
//     is what puts the term syntax under the round-trip property.
//   - A term containing "|" is omitted rather than emitted. Compositional Grammar
//     has no escape for it, so emitting it would produce text that does not parse.
//     The parser can never produce such a term, since it reads a term up to the
//     next "|"; only an expression built in code can.
func (e *Expression) String() string {
	if e == nil {
		return ""
	}
	status := e.DefinitionStatus
	if status == "" {
		status = DefStatusEquivalent
	}
	return status + " " + e.renderSubExpression()
}

// renderSubExpression renders an expression WITHOUT its definition status.
//
// That is what a nested expression is: the grammar allows a definition status on
// the top-level expression only, so `( === X )` does not parse. The parser stamps
// every nested expression with the "===" default anyway, which is why emitting it
// looked harmless until the round-trip was actually run — the rendered text then
// failed to parse at all.
//
// A nested expression carrying "<<<" therefore renders without it. Only an
// expression assembled in code can be in that state, since the parser cannot
// produce it, and the alternative is emitting text that does not parse.
func (e *Expression) renderSubExpression() string {
	var b strings.Builder
	for i, focus := range e.FocusConcepts {
		if i > 0 {
			b.WriteString(" + ")
		}
		b.WriteString(renderConceptRef(focus))
	}

	if len(e.Refinements) > 0 {
		b.WriteString(" : ")
		b.WriteString(renderRefinements(e.Refinements))
	}
	return b.String()
}

// renderRefinements writes the ungrouped attribute set and the attribute groups,
// in the order the expression holds them.
//
// The grammar puts the ungrouped set first, so parse order already has it there
// and nothing needs sorting. An expression assembled in code that puts a group
// first renders that way too — and does not parse back the same, which the
// round-trip property would report if such an expression ever reached it.
func renderRefinements(groups []AttributeGroup) string {
	parts := make([]string, 0, len(groups))
	for _, g := range groups {
		attrs := renderAttributes(g.Attributes)
		if attrs == "" {
			continue
		}
		if g.Grouped {
			parts = append(parts, "{ "+attrs+" }")
		} else {
			parts = append(parts, attrs)
		}
	}
	return strings.Join(parts, ", ")
}

func renderAttributes(attrs []Attribute) string {
	parts := make([]string, 0, len(attrs))
	for _, a := range attrs {
		parts = append(parts, renderConceptRef(a.Name)+" = "+renderAttributeValue(a.Value))
	}
	return strings.Join(parts, ", ")
}

func renderAttributeValue(v AttributeValue) string {
	switch {
	case v.Concept != nil:
		return renderConceptRef(*v.Concept)
	case v.Nested != nil:
		return "( " + v.Nested.renderSubExpression() + " )"
	case v.Concrete != nil:
		return renderConcreteValue(v.Concrete)
	default:
		// An attribute with no value at all cannot be rendered as anything that
		// parses. The parser never builds one; an expression assembled in code
		// might, and an empty rendering is the least misleading answer available
		// to a method that cannot report an error.
		return ""
	}
}

func renderConceptRef(ref ConceptRef) string {
	// A term with a pipe has no representation; see String.
	if ref.Term == "" || strings.Contains(ref.Term, "|") {
		return ref.SCTID
	}
	return ref.SCTID + " |" + ref.Term + "|"
}

func renderConcreteValue(c *ConcreteValue) string {
	switch c.Kind {
	case "integer":
		return "#" + strconv.FormatInt(c.Int, 10)
	case "decimal":
		// -1 precision renders the shortest form that reads back as the same
		// float, which is what keeps the value exact.
		//
		// The decimal POINT then has to be put back when that form has none.
		// Compositional Grammar tells an integer from a decimal by the point
		// alone, so a whole-number decimal renders as "#0" and parses back as an
		// INTEGER — a different Kind for the same number, and a silent one. Found
		// by FuzzParseRenderParse in under a second, on the input "#.0".
		text := strconv.FormatFloat(c.Float, 'f', -1, 64)
		if !strings.ContainsRune(text, '.') {
			text += ".0"
		}
		return "#" + text
	case "boolean":
		return strconv.FormatBool(c.Bool)
	default:
		return `"` + escapeSCGString(c.String) + `"`
	}
}

// escapeSCGString escapes a string literal.
//
// Only the quote and the backslash have escapes in Compositional Grammar, and
// both are required rather than cosmetic: an unescaped quote ends the literal
// early, and a value ending in a backslash would turn the closing quote into an
// escaped one and leave the literal unterminated. Every other character, control
// characters included, is written as it stands, because the grammar offers no
// escape for it and inventing one would produce text no other implementation
// reads.
func escapeSCGString(s string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return replacer.Replace(s)
}
